swagger: '2.0'
info:
  description: the description of apiinfo.
  version: 1.0.0
  title: Learn how to use swagger.
  contact:
    name: openjaw team
    email: heting.zhao@www.com
host: 'localhost:8080'
basePath: /
schemes:
  - http
  - https
tags:
  - name: Rule Management
    description: Rule management.
paths:
  /ruleSubscription:
    post:
      tags:
        - Rule Management
      summary: rule subscription
      description: rule subscription
      parameters:
        - name: subscriberReport
          in: body
          description: >-
            uuid that rule engine service generated, null if this is the first
            time.
          schema:
            $ref: '#/definitions/SubscriberReport'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/SubscriberReport'
        '400':
          description: Invalid status value
definitions:
  Rule:
    description: Rule entity of both table rule and business rule.
    type: object
    properties:
      name:
        type: string
        description: The name of a table rule or business rule.
      lastUpdated:
        type: string
        format: date
        description: Last report time of the name.
      tenantCode:
        type: string
        description: Code of the tenant.
  RuleGroup:
    description: Rule group entity of table rule or business rule.
    type: object
    properties:
      ruleGroupName:
        type: string
        description: The name of table rule's bundle or business rule's ruleset.
      ruleList:
        type: array
        items:
          $ref: '#/definitions/Rule'
        description: The subscribed rules of the group.
      lastUpdated:
        type: string
        description: Last report time of the group.
  SubscriptionInfo:
    type: object
    description: Read from subscriber’s own properties.
    properties:
      tableRules:
        type: array
        items:
          $ref: '#/definitions/RuleGroup'
        description: Group list of table rule.
      businessRules:
        type: array
        items:
          $ref: '#/definitions/RuleGroup'
        description: Group list of table rule business rule.
  SubscriberReport:
    description: The data model of subscriber report.
    type: object
    properties:
      key:
        type: string
        description: >-
          UUID that rule engine service generated, null if this is the first
          time.
      name:
        type: string
        description: 'Subscriber service name, read from subscriber’s own properties.'
      status:
        type: string
        description: success or error (status of the subscription)
      address:
        type: string
        description: Subscriber’s IP address.
      lastUpdated:
        type: string
        format: date
        description: Timestamp of when this subscriber reload itself last time.
      lastUpdated2:
        type: string
        format: timestamp
      lastUpdated3:
        type: string
        format: datetime
      metadata:
        type: string
        description: >-
          metadata of the subscriber it wants to use, such as subscriber’s
          service version.
      subscriptionInfo:
        description: sdf
        $ref: '#/definitions/SubscriptionInfo'