swagger: '2.0'
info:
  description: the description of apiinfo.
  version: 1.0.0
  title: Learn how to use swagger.
  contact:
    name: openjaw team
    email: heting.zhao@www.com
host: 'localhost:8080'
basePath: /
schemes:
  - http
  - https
tags:
  - name: FileManagement
    description: DownloadZip
paths:
  /downloadZipInString:
    get:
      tags:
        - FileManagement
      summary: Load rules from SDK.
      description: Load rules from SDK.
      responses:
        '200':
          description: Return a zip file.
          schema:
            type: string
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
  /downLoadZipInFile:
    get:
      tags:
        - FileManagement
      summary: Load rules from SDK.
      description: Load rules from SDK.
      produces:
        - application/octet-stream
      consumes:
        - application/octet-stream
      responses:
        '200':
          description: Return a zip file.
          schema:
            type: file
        '400':
          description: Invalid ID supplied
        '404':
          description: not found
  /downLoadZipInBytes:
    get:
      tags:
        - FileManagement
      summary: Load rules from SDK.
      description: Load rules from SDK.
      responses:
        '200':
          description: Return a zip file.
          schema:
            type: array
            items:
              type: string
        '400':
          description: Invalid ID supplied
        '404':
          description: not found
