swagger: '2.0'
info:
  description: Api info of rule engine service.
  version: 1.0.0
  title: Rule Engine Service.
  contact:
    name: Dragon Fire Team
    email: team_dragonfire@www.com
host: 'localhost:8080'
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: demo
    description: Interfaces for rule management.
paths:
  /demo:
    get:
      tags:
        - demo
      operationId: demo
      description: demo.
      consumes: []
      parameters:
        - $ref: '#/parameters/brand'
parameters:
  brand:
    name: Brand
    in: header
    description: Requested brand
    type: string