swagger: '2.0'
info:
  description: the description of apiinfo.
  version: 1.0.0
  title: Learn how to use swagger.
  contact:
    name: openjaw team
    email: heting.zhao@www.com
host: 'localhost:8080'
basePath: /
schemes:
  - http
  - https
tags:
  - name: RuleManagement
    description: Download Zip
paths:
  /downLoadZipInFile:
    get:
      tags:
        - RuleManagement
      summary: Load rules from SDK.
      description: >-
        Return a zip file as a byte array in customised response entity,then the
        file can be downloaded from front end.
      produces:
        - application/octet-stream
      consumes:
        - application/octet-stream
      responses:
        '200':
          description: Return a zip file.
          schema:
            type: file
        '400':
          description: Invalid ID supplied
        '404':
          description: not found
  /downLoadZipInBytes:
    get:
      tags:
        - RuleManagement
      summary: Load rules from SDK.
      description: >-
        Return a zip file as a byte array in customised response entity,then the
        client can get the array.
      responses:
        '200':
          description: >-
            Return a zip file as a byte array in customised response entity
            successfully.
          schema:
            $ref: '#/definitions/ruleResponse'
        '400':
          description: Invalid ID supplied
        '404':
          description: not found
definitions:
  ruleResponse:
    description: transform the result
    type: object
    properties:
      ruleInBytes:
        type: string
        format: byte
        description: put zip file in a byte array.
