swagger: '2.0'
info:
  description: the description of apiinfo.
  version: 1.0.0
  title: Learn how to use swagger.
  contact:
    name: openjaw team
    email: heting.zhao@www.com
host: GrandWorldM
basePath: /
tags:
  - name: Rule Management
    description: Rule Store And Access
paths:
  /ruleBundles:
    post:
      tags:
        - Rule Management
      summary: Accept rule pushes request from console to store it.
      description: Accept rule pushes request from console to store it.
      operationId: pushRuleBundles
      produces:
        - application/json
      consumes:
        - multipart/form-data
      parameters:
        - name: types
          in: path
          description: rule types
          required: true
          type: string
        - name: tenantId
          in: path
          description: tenant id
          required: true
          type: string
        - name: version
          in: path
          description: rule version
          required: true
          type: string
        - name: ruleZip
          in: formData
          description: rule bundles
          required: true
          type: file
      responses:
        '200':
          description: OK
          schema:
            properties:
              uuid:
                type: string
                description: RuleBundle ID
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
  /rules:
    get:
      tags:
        - Rule Management
      summary: Load rules from SDK.
      description: Load rules from SDK.
      produces:
        - application/octet-stream
      consumes:
        - application/octet-stream
      responses:
        '200':
          description: Return a zip file.
          schema:
            type: array
            items:
              type: string

